### PR TITLE
Night mode - red channel only

### PR DESCRIPTION
**Pull request by nzawirski**
I added a "night mode" effect that leaves only red channel to reduce eye strain in low light conditions.

### CODE REVIEW

**Comment by G-dH** [comment]
The built-in Night Light doesn't work for you?

**Comment by nzawirski** [comment]
The built-in night light is great in most cases. But i wanted something more extreme for specific cases. Night light only slightly filters blue channel, while i was looking for something that eliminates both blue and green leaving only the red which is the longest wavelenght a thus doesn't require my eyes to readjust that much when i want to do something on my device at night. I realise this is quite odd and specific use case 😅 but it was something i was specifically looking for and couldn't find. This extension seemed like a good opportunity to introduce something like that as a extra feature

**Comment by G-dH** [comment]
The Night Light can filter the blue channel completely if you set it to full, but it doesn't filter the green light. I'm not colorblind, but watching only the red channel on the screen is really unpleasant experience for me with missing content. Using the Strength slider amplifies also the blue channel, so it's useless. If you add at least half the information from the green channel, the experience is much better. But since I perceive the red light without any loss, the red parts of the screen become too aggressive - so my perfect night time filter is Night Light at full + Deuteranopia correction :)

**Comment by G-dH** [comment]
And one more suggestion - my _Custom Hot Corners - Extended_ extension offers _Custom Color Tint_ action, you can set the color on _Options_ page of its Settings window. This uses `Clutter.ColorizeEffect.tint` that makes colorized desaturated image, which is usable with only the red channel.

**Comment by nzawirski** [comment]
Thank you for explanations and suggesting Custom Hot Corners Extended. It's Color Tint action is even more suitable for what i was looking for, and colorizing desaturated image surely is a better solution than leaving only red channel. I thought about that tbh but settled for a simpler and hackier solution. 
Anyway, since Color Tint action satisfies my use case i think there is no point in merging this PR anymore so i'll just close it. Thanks again, and happy holidays.

**Comment by G-dH** [comment]
Happy holidays!

**Pull request closed without merging**
